# NumPy Basics Exercises

The link to the list of exercises: [W3 resources](https://www.w3resource.com/python-exercises/numpy/basic/index.php)

In [1]:
import numpy as np

In [2]:
print("Numpy version: ", np.__version__)
print("Numpy build configuration: ", np.show_config())

Numpy version:  2.3.3
Build Dependencies:
  blas:
    detection method: system
    found: true
    include directory: unknown
    lib directory: unknown
    name: accelerate
    openblas configuration: unknown
    pc file directory: unknown
    version: unknown
  lapack:
    detection method: system
    found: true
    include directory: unknown
    lib directory: unknown
    name: accelerate
    openblas configuration: unknown
    pc file directory: unknown
    version: unknown
Compilers:
  c:
    commands: cc
    linker: ld64
    name: clang
    version: 15.0.0
  c++:
    commands: c++
    linker: ld64
    name: clang
    version: 15.0.0
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.1.3
Machine Information:
  build:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
  host:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
Python Information:
  path: /private/var/folders/y6/nj790rtn62lfktb1sh__79hc00

In [3]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

In [4]:
np.random.seed(64)

array_random_with_0 = np.random.randint(low=0, high=5, size=(5))
array_random_without_0 = np.random.randint(low=1, high=6, size=(5))

print(array_random_with_0.shape)
print(array_random_with_0)
print(array_random_without_0.shape)
print(array_random_without_0)

print(array_random_with_0.all()) # So there is 0 in the array
print(array_random_without_0.all()) # So there is no 0 in the array

# it works differently for 2d, there are cases like with axis parameter
#   - axis = 0 it will check column wise and then returns a boolean per column
#   - axis = 1 it will check row wise and then returns a boolean per row

(5,)
[4 1 4 3 0]
(5,)
[1 3 1 3 1]
False
True


In [5]:
np.random.seed(64)

print(array_random_with_0.shape)
print(array_random_with_0)
print(array_random_without_0.shape)
print(array_random_without_0)

print(array_random_with_0.any())
print(array_random_without_0.any())

(5,)
[4 1 4 3 0]
(5,)
[1 3 1 3 1]
True
True


In [6]:
a = np.array([1, 0, np.nan, np.inf])

print("Is finite: ", np.isfinite(a))

Is finite:  [ True  True False False]


In [7]:
a = np.array([-np.inf, np.inf, np.nan, 0, 1, 3])

print("Test for positive INF: ", np.isposinf(a))
print("Test for negativate INF: ", np.isneginf(a))

Test for positive INF:  [False  True False False False False]
Test for negativate INF:  [ True False False False False False]


In [8]:
print("Test for NaN: ", np.isnan(a))

Test for NaN:  [False False  True False False False]


In [9]:
a = np.array([1,2,3,4,5])
a_1 = np.array([1,3,2,4,5])
b = np.array([1,2,3,4,5])

print("a and b are equal or not, element wise: ", np.equal(a, b))
print("a_1 and b are equal or not, element wise: ", np.equal(a_1, b))

# Checking if the two arrays are element-wise equal within a tolerance and printing the result
print(np.allclose([1e10,1e-7], [1.00001e10,1e-8]))
print(np.allclose([1e10,1e-8], [1.00001e10,1e-9]))
print(np.allclose([1e10,1e-8], [1.0001e10,1e-9]))

a and b are equal or not, element wise:  [ True  True  True  True  True]
a_1 and b are equal or not, element wise:  [ True False False  True  True]
False
True
False


In [10]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

print("Element wise comparison greater: ", np.greater(a, b))
print("Element wise comparison lesser: ", np.less(a, b))
print("Element wise comparison greater equal: ", np.greater_equal(a, b))
print("Element wise comparison lesser equal: ", np.less_equal(a, b))

Element wise comparison greater:  [False False False False False]
Element wise comparison lesser:  [ True  True  True  True  True]
Element wise comparison greater equal:  [False False False False False]
Element wise comparison lesser equal:  [ True  True  True  True  True]


In [11]:
a = np.array([1,2,3,4,5.000001])
b = np.array([1,2,3,4,5])

print("Equal or not: ", np.equal(a, b))
print("Equal or not with tolerance: ", np.allclose(a, b))

Equal or not:  [ True  True  True  True False]
Equal or not with tolerance:  True


In [12]:
a = np.array([1,7,13,105])
print("Size of the array: ", a.size * a.itemsize)

Size of the array:  32


In [16]:
a = np.array([0]*10 + [1]*10 + [5]*10)
print(a)
print(a.shape)

zeros_a = np.zeros(10)
ones_a = np.ones(10)
fives_a = np.ones(10) * 5

print(zeros_a, ones_a, fives_a)

[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 5 5 5 5 5 5 5 5 5 5]
(30,)
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [18]:
a = np.arange(start=30, stop=71)

print(a)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [20]:
a = np.arange(start=30, stop=71, step=2)

print(a)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [21]:
a = np.identity(3)

print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [26]:
np.random.seed(64)

print("Random number between 0 and 1: ", np.random.rand())

Random number between 0 and 1:  0.3790985254337701


In [32]:
np.random.seed(64)

print("Random Array from standard normal: \n")
print(np.random.normal(0, 1, 15))

Random Array from standard normal: 

[ 1.10032294 -1.98262742 -1.15024951  2.19291636 -1.90143503 -0.43389669
 -1.13558187 -1.03329507 -2.37195862  0.70333809  0.38484212  1.7504858
 -1.19506926  0.29512768  0.04832088]


In [33]:
a = np.arange(15, 56)
print(a[1:-1])

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]


In [38]:
np.random.seed(64)

a = np.random.randint(1, 5, (3,4))

print(a)

for i in np.nditer(a):
    print(i, end=" ")

[[1 3 4 3]
 [3 2 1 4]
 [2 1 4 1]]
1 3 4 3 3 2 1 4 2 1 4 1 

In [40]:
a = np.arange(5, 51, 5)

print(a)
print(a.shape)

[ 5 10 15 20 25 30 35 40 45 50]
(10,)


In [42]:
a = np.arange(0, 21)
a[(a >= 9) & (a <= 15)] *= -1

print(a)

[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [43]:
np.random.seed(64)

print("random integers between 0 and 10 of size 5: ", np.random.randint(0, 11, 5))

random integers between 0 and 10 of size 5:  [4 6 7 6 6]


In [44]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

print("Multiplication of 2 vectors: ", np.multiply(a, b))

Multiplication of 2 vectors:  [ 5 12 21 32 45]


In [48]:
a = np.arange(10, 22)
a = a.reshape((3,4))
print(a)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [50]:
a.shape

(3, 4)

In [51]:
a = np.identity(3)

print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [54]:
a = np.ones(100).reshape((10,10))

a[1:-1, 1:-1] = 0

print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [58]:
a = np.diag([1,2,3,4,5])

print(a)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [64]:
a = 1 - np.identity(4)

print(a)

[[0. 1. 1. 1.]
 [1. 0. 1. 1.]
 [1. 1. 0. 1.]
 [1. 1. 1. 0.]]


In [71]:
np.random.seed(64)

a = np.random.randint(low=1, high=10, size=(3,3,3))

print(a)

[[[5 7 8]
  [7 7 2]
  [5 4 6]]

 [[1 9 7]
  [9 3 1]
  [2 5 3]]

 [[7 5 6]
  [1 6 7]
  [3 7 3]]]


In [ ]:
np.random.seed(64)

a = np.random.randint(low=1, high=5, size=(3,3))

print(a, "\n\n")

print("Sum of all elements: ", np.sum(a))
print("Sum of all columns: ", np.sum(a, axis=0))
print("Sum of all rows: ", np.sum(a, axis=1))

[[1 3 4]
 [3 3 2]
 [1 4 2]] 


Sum of all elements:  23
Sum of all rows:  [ 5 10  8]
Sum of all columns:  [8 8 7]


In [79]:
np.random.seed(64)

a = np.random.randint(1, 5, (3, 3))
b = np.random.randint(5, 9, (3, 3))

print(b)

print(np.inner(a, b))

[[5 8 5]
 [7 7 6]
 [5 7 5]]
[[49 52 46]
 [49 54 46]
 [47 47 43]]


In [85]:
np.random.seed(64)

a = np.random.randint(1,5,3)

print(a)

print(np.add(a, b))

[1 3 4]
[[ 6 11  9]
 [ 8 10 10]
 [ 6 10  9]]


In [86]:
np.save("test.npy", np.add(a,b))
c = np.load("test.npy")
print(c)

[[ 6 11  9]
 [ 8 10 10]
 [ 6 10  9]]


In [87]:
np.savetxt("test.txt", np.add(a,b))
d = np.loadtxt("test.txt")
print(d)

[[ 6. 11.  9.]
 [ 8. 10. 10.]
 [ 6. 10.  9.]]


In [97]:
e = a.byteswap()
print(e)
e = e.byteswap()
print(e)


a_bytes = e.tobytes()
a_nbytes = np.frombuffer(a_bytes, dtype=a.dtype)

print(a_bytes)
print(a_nbytes)

[ 72057594037927936 216172782113783808 288230376151711744]
[1 3 4]
b'\x01\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00'
[1 3 4]


In [100]:
l = [1,2,3,4,5]
a = np.array(l)

a = a.tolist()

print(a)
print(l)

print("Checking if the first l and numpy_to_list a same: ", a == l)

[1, 2, 3, 4, 5]
[1, 2, 3, 4, 5]
Checking if the first l and numpy_to_list a same:  True


In [107]:
a = np.float32(0)
print(type(a))

a = a.item()

print(type(a))

<class 'numpy.float32'>
<class 'float'>


In [118]:
np.random.seed(64)

a = np.random.randint(0,3,(3,3))

print(a)

sum_a = 0

for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        if a[i][j] == 0 and i < a.shape[1]-1:
            a[i + 1][j] = 0
        sum_a += a[i][j]
        
                
print(sum_a)

[[0 2 2]
 [2 1 0]
 [1 0 0]]
5


In [126]:
np.random.seed(64)

print(np.random.choice(7,7))
print(np.random.choice(7,7, replace=False))
print(np.random.choice(7,7, p=[0.1, 0.2, 0.1, 0.2, 0.2, 0.1, 0.1]))
print(np.random.choice(7,7, p=[0.1, 0.2, 0.1, 0.2, 0.2, 0.1, 0.1], replace=False))

[4 6 6 6 1 4 3]
[4 1 3 2 6 0 5]
[6 5 3 6 3 1 6]
[6 5 4 2 3 0 1]


In [142]:
np.random.seed(64)

a = np.random.randint(0,5, (4,4))

print(a)

# a[0], a[-1] = a[-1], a[0]

# Also advanced indexing
a[[0,-1],:] = a[[-1,0],:]

print(a)

[[4 1 4 3]
 [0 0 2 0]
 [2 0 1 4]
 [2 4 3 4]]
[[2 4 3 4]
 [0 0 2 0]
 [2 0 1 4]
 [4 1 4 3]]


In [135]:
nums = np.array([[5.54, 3.38, 7.99],
              [3.54, 8.32, 6.99],
              [1.54, 2.39, 9.29]])

print(nums)

# Replacing based on a condition
print(np.where(nums > 2, 10, nums))
print(np.where(nums < 2, 10, nums))
print()
print(np.where([nums >= 2, nums <= 2, nums == 2], [10, 10, 10], nums))

[[5.54 3.38 7.99]
 [3.54 8.32 6.99]
 [1.54 2.39 9.29]]
[[10.   10.   10.  ]
 [10.   10.   10.  ]
 [ 1.54 10.   10.  ]]
[[ 5.54  3.38  7.99]
 [ 3.54  8.32  6.99]
 [10.    2.39  9.29]]

[[[10.   10.   10.  ]
  [10.   10.   10.  ]
  [ 1.54 10.   10.  ]]

 [[ 5.54  3.38  7.99]
  [ 3.54  8.32  6.99]
  [10.    2.39  9.29]]

 [[ 5.54  3.38  7.99]
  [ 3.54  8.32  6.99]
  [ 1.54  2.39  9.29]]]


In [144]:
# Tips for advanced slicing and indexing:
# Comma separates axes. - a[i, j] means: row i, column j (for 2D arrays). a[i, j, k] for 3D arrays, and so on.
# List/array means “pick these specific indices.” - a[[0, 2], [1, 3]] picks elements at (0,1) and (2,3).
# Slice (:) means “pick a range.” - Uses : to select a range. a[1:3, 2:4] means: rows 1 to 2, columns 2 to 3.

In [147]:
a = np.zeros((8,8))

a[::2, 1::2] = 1
a[1::2, ::2] = 1

print(a)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [152]:
a = np.array([10,20,30])

print(np.append(a, [40,50,60,70,80,90]))

[10 20 30 40 50 60 70 80 90]


In [161]:
np.random.seed(64)

print(np.empty((3,4)))

print(np.full((3,4), 6))

[[3.e-323 3.e-323 3.e-323 3.e-323]
 [3.e-323 3.e-323 3.e-323 3.e-323]
 [3.e-323 3.e-323 3.e-323 3.e-323]]
[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]


In [162]:
a = np.array([0,1,2,4,6])
b = np.array([1,3,4])

print(np.intersect1d(a, b))

[1 4]


In [163]:
a = np.array([1,1,1,2,2,2,3,3,3,4,4,4,5,5,5])

print(np.unique(a))
print(np.unique_all(a))
print(np.unique_counts(a))
print(np.unique_inverse(a))
print(np.unique_values(a))

[1 2 3 4 5]
UniqueAllResult(values=array([1, 2, 3, 4, 5]), indices=array([ 0,  3,  6,  9, 12]), inverse_indices=array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4]), counts=array([3, 3, 3, 3, 3]))
UniqueCountsResult(values=array([1, 2, 3, 4, 5]), counts=array([3, 3, 3, 3, 3]))
UniqueInverseResult(values=array([1, 2, 3, 4, 5]), inverse_indices=array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4]))
[5 4 3 2 1]


In [166]:
array1 = np.array([0, 10, 20, 40, 60, 80])
array2 = [10, 30, 40, 50, 70]

print(np.setdiff1d(array1, array2))
print(np.setxor1d(array1, array2))
print(np.union1d(array1, array2))

[ 0 20 60 80]
[ 0 20 30 50 60 70 80]
[ 0 10 20 30 40 50 60 70 80]


In [172]:
a = np.array([1,2,3,4])

print(np.append(a,3*[a]))
print(np.tile(a,3))

[1 2 3 4 1 2 3 4 1 2 3 4 1 2 3 4]
[1 2 3 4 1 2 3 4 1 2 3 4]


In [174]:
a = np.repeat(3, 4)
print(a)

a = np.array([[1,2], [3,4]])
print(np.repeat(a, 3))

[3 3 3 3]
[1 1 1 2 2 2 3 3 3 4 4 4]


In [ ]:
a = np.array([[1,2], [3,4]])

print(np.max(a))
print(np.argmax(a))

4
3


In [177]:
a.flatten()

array([1, 2, 3, 4])

In [181]:
a.reshape((4,1))

array([[1],
       [2],
       [3],
       [4]])

In [183]:
a = a.astype("float32")
print(a.dtype)
a = a.astype("float64")
print(a.dtype)

float32
float64


In [187]:
a = np.linspace(2.5, 6.5, 50)
b = np.logspace(2, 5, 50, endpoint=False)

print(a)
print(b)

[2.5        2.58163265 2.66326531 2.74489796 2.82653061 2.90816327
 2.98979592 3.07142857 3.15306122 3.23469388 3.31632653 3.39795918
 3.47959184 3.56122449 3.64285714 3.7244898  3.80612245 3.8877551
 3.96938776 4.05102041 4.13265306 4.21428571 4.29591837 4.37755102
 4.45918367 4.54081633 4.62244898 4.70408163 4.78571429 4.86734694
 4.94897959 5.03061224 5.1122449  5.19387755 5.2755102  5.35714286
 5.43877551 5.52040816 5.60204082 5.68367347 5.76530612 5.84693878
 5.92857143 6.01020408 6.09183673 6.17346939 6.25510204 6.33673469
 6.41836735 6.5       ]
[  100.           114.81536215   131.82567386   151.35612484
   173.78008287   199.5262315    229.08676528   263.02679919
   301.99517204   346.73685045   398.10717055   457.08818961
   524.80746025   602.55958607   691.83097092   794.32823472
   912.01083936  1047.12854805  1202.26443462  1380.3842646
  1584.89319246  1819.70085861  2089.29613085  2398.83291902
  2754.22870334  3162.27766017  3630.7805477   4168.6938347
  4786.30092323 

In [194]:
print(np.tri(4,3,-1))

[[0. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]


In [195]:
print(np.triu(np.arange(2,14).reshape(4,3), -1))

[[ 2  3  4]
 [ 5  6  7]
 [ 0  9 10]
 [ 0  0 13]]


In [197]:
a.flat[3]

np.float64(2.7448979591836733)

In [198]:
a = np.array([[1,2,3]])

print(np.swapaxes(a, 0, 1))

[[1]
 [2]
 [3]]


In [201]:
a = np.zeros((2, 3, 4))
b = np.swapaxes(a, 0, 2)  # swaps first and third axes
print(b.shape)  # (4, 3, 2)
print(a)
print()
print(b)

(4, 3, 2)
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [202]:
a = np.zeros((2,3,4))

print(np.moveaxis(a, 0, -1).shape)
print(np.moveaxis(a, 0, -2).shape)
print(np.moveaxis(a, -1, 0).shape)
print(np.moveaxis(a, -2, 0).shape)

(3, 4, 2)
(3, 2, 4)
(4, 2, 3)
(3, 2, 4)


In [205]:
x = 12.0

print(np.atleast_1d(x))
print(np.atleast_1d(1, [3, 4]))

# There is also atleast_2d and atleast_3d

[12.]
(array([1]), array([3, 4]))


In [211]:
a = np.zeros((3,4))

print(a)
print()

a = np.expand_dims(a, axis=1)
print(a)
print()
print(a.shape)

a = np.expand_dims(a, axis=1)
print(a)
print()
print(a.shape)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[[0. 0. 0. 0.]]

 [[0. 0. 0. 0.]]

 [[0. 0. 0. 0.]]]

(3, 1, 4)
[[[[0. 0. 0. 0.]]]


 [[[0. 0. 0. 0.]]]


 [[[0. 0. 0. 0.]]]]

(3, 1, 1, 4)


In [212]:
a = np.zeros((3,4))

a = np.expand_dims(a, axis=1)

print(a.shape)

a = np.squeeze(a)

print(a.shape)

(3, 1, 4)
(3, 4)


In [218]:
a = np.zeros((3,4))

print(a)
print()

a = np.expand_dims(a, axis=1)
print(a)
print()
print(a.shape)

a = np.expand_dims(a, axis=1)
print(a)
print()
print(a.shape)

a = np.squeeze(a, axis=2)
a = np.squeeze(a, axis=1)
print(a.shape)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[[0. 0. 0. 0.]]

 [[0. 0. 0. 0.]]

 [[0. 0. 0. 0.]]]

(3, 1, 4)
[[[[0. 0. 0. 0.]]]


 [[[0. 0. 0. 0.]]]


 [[[0. 0. 0. 0.]]]]

(3, 1, 1, 4)
(3, 4)


In [221]:
a = np.array([[0, 1, 3], [5, 7, 9]])
b = np.array([[0, 2, 4], [6, 8, 10]])

c = np.concat((a,b), axis=1)

print(c)

[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


In [222]:
a = np.array([10,20,30])
b = np.array([40,50,60])

c = np.column_stack((a,b))

print(c)

[[10 40]
 [20 50]
 [30 60]]


In [224]:
d = np.vstack((a,b))

print(d)

[[10 20 30]
 [40 50 60]]


In [225]:
a = np.array([[10], [20], [30]])
b = np.array([[40], [50], [60]])

c = np.dstack((a,b))

print(c)

[[[10 40]]

 [[20 50]]

 [[30 60]]]


In [226]:
a = np.arange(1,15)

print(np.split(a, [2,6]))

[array([1, 2]), array([3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12, 13, 14])]


In [227]:
a = np.array([1,2,3,0,0,0,4,5,6])

print(np.count_nonzero(a))

6


In [229]:
a = np.zeros((5,5))

a += np.arange(5)

print(a)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [230]:
never_gonna_use_this = np.zeros(10)

never_gonna_use_this.flags.writeable = False

In [232]:
never_gonna_use_this[0] = 1

ValueError: assignment destination is read-only

In [ ]:
x = np.array([ 0.26153123, 0.52760141, 0.5718299, 0.5927067, 0.7831874, 0.69746349,
               0.35399976, 0.99469633, 0.0694458, 0.54711478])

print(x)

np.set_printoptions(precision=10)

# There is also suppress to suppress scientific notation in array printing

print(x)

[0.262 0.528 0.572 0.593 0.783 0.697 0.354 0.995 0.069 0.547]
[0.26153123 0.52760141 0.5718299  0.5927067  0.7831874  0.69746349
 0.35399976 0.99469633 0.0694458  0.54711478]


In [237]:
iterable = (x for x in range(10))

print(np.fromiter(iterable, np.int32))

[0 1 2 3 4 5 6 7 8 9]


In [238]:
x = np.array([[20, 20, 20, 0],
              [0, 20, 20, 20],
              [0, 20, 20, 20],
              [20, 20, 20, 0],
              [10, 20, 20, 20]])

np.unique(x, axis=0)

array([[ 0, 20, 20, 20],
       [10, 20, 20, 20],
       [20, 20, 20,  0]])

In [239]:
np.delete(x, [[0,0], [1,0]])

array([20,  0,  0, 20, 20, 20,  0, 20, 20, 20, 20, 20, 20,  0, 10, 20, 20,
       20])

In [248]:
arra = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arra)

# result = arra[:, [1, 2]]
result = arra[:, -1:-3:-1][:,::-1]

print(result)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]
 [8 9]]


In [268]:
x = np.arange(16.0).reshape(2, 2, 4)

print(x)

print(x.shape)

np.vsplit(x, [1])[0].shape

[[[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]]

 [[ 8.  9. 10. 11.]
  [12. 13. 14. 15.]]]
(2, 2, 4)


(1, 2, 4)